# Configuration for actions/labeler
# https://github.com/actions/labeler

# === Content ===

guide:
  - changed-files:
      - any-glob-to-any-file:
          - src/content/docs/guides/**

tutorial:
  - changed-files:
      - any-glob-to-any-file:
          - src/content/docs/tutorials/**

explanation:
  - changed-files:
      - any-glob-to-any-file:
          - src/content/docs/explanations/**

reference:
  - changed-files:
      - any-glob-to-any-file:
          - src/content/docs/reference/**

integration:
  - changed-files:
      - any-glob-to-any-file:
          - src/content/docs/integrations/**

# === Infrastructure ===

site:
  - changed-files:
      - any-glob-to-any-file:
          - "!src/content/**"
