// Conditionally load OCSF version (generated by sync-ocsf.mjs)
const ocsfModules = import.meta.glob("../ocsf-version.mjs", { eager: true });
const ocsfVersion = Object.values(ocsfModules)[0]?.OCSF_VERSION ?? null;

// Generate all redirects for the documentation
export function generateRedirects() {
  const redirects = {};

  // Static redirects
  redirects["/discord"] = "https://discord.gg/xqbDgVTCxZ";
  redirects["/sbom"] =
    "https://github.com/tenzir/tenzir/releases/latest/download/tenzir.spdx.json";

  // OCSF latest version redirect (only when OCSF docs are generated)
  // Note: Only base redirect works; Astro doesn't support dynamic segments in static redirects
  if (ocsfVersion) {
    redirects["/reference/ocsf/latest"] = `/reference/ocsf/${ocsfVersion}`;
  }

  return redirects;
}
