id: zeek
name: Zeek
author: Tenzir
author_icon: https://github.com/tenzir.png
description: |
  Example package for Zeek OCSF mappings.

  For a complete package, see https://github.com/tenzir/library.
