[aliases]
bootstrap = "bun run lefthook:install"
setup = "wt hook pre-start --yes"
run = "wt step tether -- bun run dev -- --port {{ (repo ~ '-' ~ branch) | hash_port }}"

[pre-start]
copy = "wt step copy-ignored"
deps = "bun install"

[post-start]
docs = "wt -y run"

[pre-merge]
lint = "bun run lint"

[list]
url = "http://localhost:{{ (repo ~ '-' ~ branch) | hash_port }}"
