import { defineRouteMiddleware } from "@astrojs/starlight/route-data";
import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const partialHeadingsFile = resolve(
  __dirname,
  "generated/partial-headings.json",
);

interface HeadingInfo {
  depth: number;
  slug: string;
  text: string;
}

// Load partial headings map (generated by remark-partial-headings plugin)
function loadPartialHeadings(): Record<string, HeadingInfo[]> {
  if (existsSync(partialHeadingsFile)) {
    try {
      const content = readFileSync(partialHeadingsFile, "utf-8");
      return JSON.parse(content);
    } catch {
      return {};
    }
  }
  return {};
}

// Cache the loaded headings
let partialHeadingsMap: Record<string, HeadingInfo[]> | null = null;

function getPartialHeadings(): Record<string, HeadingInfo[]> {
  if (!partialHeadingsMap) {
    partialHeadingsMap = loadPartialHeadings();
  }
  return partialHeadingsMap;
}

export const onRequest = defineRouteMiddleware((context) => {
  context.locals.starlightRoute.siteTitleHref = "https://tenzir.com";

  // Inject partial headings into TOC
  const slug = context.locals.starlightRoute.slug;
  const partialHeadings = getPartialHeadings()[slug];

  if (partialHeadings && partialHeadings.length > 0) {
    const toc = context.locals.starlightRoute.toc;
    if (toc?.items) {
      // Find the Examples heading to insert before it (h3s should go under the last h2)
      const examplesIndex = toc.items.findIndex(
        (item) => item.slug === "examples",
      );

      // Convert headings to TocItem format
      // - Strip backticks from text for clean rendering
      // - h3 headings (depth 3) should be nested under the previous h2
      const newItems = partialHeadings.map((h) => ({
        depth: h.depth,
        slug: h.slug,
        text: h.text.replace(/`/g, ""), // Strip backticks
        children: [],
      }));

      // For h3 headings, we need to nest them under the appropriate h2
      // Find the last h2 item before Examples (usually "url: string" or similar)
      const insertIndex =
        examplesIndex !== -1 ? examplesIndex : toc.items.length;

      // Find the last h2 before the insert point to nest h3s under
      let lastH2Index = -1;
      for (let i = insertIndex - 1; i >= 0; i--) {
        if (toc.items[i].depth === 2) {
          lastH2Index = i;
          break;
        }
      }

      if (lastH2Index !== -1 && newItems.every((item) => item.depth === 3)) {
        // All items are h3, nest them under the last h2's children
        toc.items[lastH2Index].children.push(...newItems);
      } else {
        // Mixed depths or no h2 found, insert at top level
        if (examplesIndex !== -1) {
          toc.items.splice(examplesIndex, 0, ...newItems);
        } else {
          toc.items.push(...newItems);
        }
      }
    }
  }
});
