import { section } from "./sidebar-sections";
import {
  nodeAPISidebarGroup,
  platformAPISidebarGroup,
} from "./sidebar-shared-groups.js";

// Conditionally load OCSF sidebar (generated by sync-ocsf.mjs)
const ocsfModules = import.meta.glob<{ ocsfSidebar: object }>(
  "./sidebar-ocsf.generated.ts",
  { eager: true },
);
const ocsfGenerated = Object.values(ocsfModules)[0];
const ocsfSidebar = ocsfGenerated?.ocsfSidebar ?? null;

export const guides = [
  section(
    "Get Started",
    [
      "guides/quickstart",
      {
        label: "Installation",
        collapsed: true,
        items: ["guides/installation", "guides/installation/create-account"],
      },
      {
        label: "Basic Usage",
        collapsed: true,
        items: [
          "guides/basic-usage/run-pipelines",
          "guides/basic-usage/manage-a-pipeline",
        ],
      },
    ],
    "lightbulb",
  ),
  section(
    "Setup",
    [
      {
        label: "Node Setup",
        collapsed: true,
        items: [
          "guides/node-setup",
          "guides/node-setup/provision-a-node",
          "guides/node-setup/size-a-node",
          "guides/node-setup/deploy-a-node",
          "guides/node-setup/configure-a-node",
          "guides/node-setup/configure-tls",
          "guides/node-setup/start-the-api",
          "guides/node-setup/tune-performance",
        ],
      },
      {
        label: "Platform Setup",
        collapsed: true,
        items: [
          "guides/platform-setup",
          "guides/platform-setup/deploy-on-aws",
          "guides/platform-setup/choose-a-scenario",
          "guides/platform-setup/configure-reverse-proxy",
          "guides/platform-setup/configure-internal-services",
          "guides/platform-setup/configure-identity-provider",
          "guides/platform-setup/configure-database",
          "guides/platform-setup/configure-blob-storage",
          "guides/platform-setup/configure-secret-store",
          "guides/platform-setup/run-the-platform",
        ],
      },
      {
        label: "Platform Management",
        collapsed: true,
        items: [
          "guides/platform-management/configure-workspaces",
          "guides/platform-management/configure-dashboards",
          "guides/platform-management/use-ephemeral-nodes",
        ],
      },
      {
        label: "AI Workbench",
        collapsed: true,
        items: [
          { label: "Overview", link: "guides/ai-workbench" },
          "guides/ai-workbench/install-mcp-server",
          "guides/ai-workbench/configure-your-agent",
          "guides/ai-workbench/use-claude-plugins",
          "guides/ai-workbench/use-documentation-skill",
        ],
      },
    ],
    "gear",
  ),
  section(
    "Work with Data",
    [
      {
        label: "Collecting",
        collapsed: true,
        items: [
          { label: "Overview", link: "guides/collecting" },
          "guides/collecting/read-and-watch-files",
          "guides/collecting/fetch-via-http-and-apis",
          "guides/collecting/read-from-message-brokers",
          "guides/collecting/get-data-from-the-network",
        ],
      },
      {
        label: "Parsing",
        collapsed: true,
        items: [
          "guides/parsing/parse-delimited-text",
          "guides/parsing/parse-binary-data",
          "guides/parsing/parse-string-fields",
        ],
      },
      {
        label: "Transformation",
        collapsed: true,
        items: [
          "guides/transformation/filter-and-select-data",
          "guides/transformation/transform-values",
          "guides/transformation/manipulate-strings",
          "guides/transformation/work-with-time",
          "guides/transformation/shape-lists-and-records",
          "guides/transformation/reshape-complex-data",
          "guides/transformation/convert-data-formats",
        ],
      },
      {
        label: "Normalization",
        collapsed: true,
        items: [
          { label: "Overview", link: "guides/normalization" },
          "guides/normalization/clean-up-values",
          "guides/normalization/map-to-ocsf",
          "guides/normalization/map-to-other-schemas",
        ],
      },
      {
        label: "Enrichment",
        collapsed: true,
        items: [
          "guides/enrichment/work-with-lookup-tables",
          "guides/enrichment/enrich-with-network-inventory",
          "guides/enrichment/enrich-with-threat-intel",
          "guides/enrichment/execute-sigma-rules",
        ],
      },
      {
        label: "Optimization",
        collapsed: true,
        items: [
          "guides/optimization/slice-and-sample-data",
          "guides/optimization/deduplicate-events",
        ],
      },
      {
        label: "Routing",
        collapsed: true,
        items: [
          "guides/routing/send-to-destinations",
          "guides/routing/split-and-merge-streams",
          "guides/routing/load-balance-pipelines",
        ],
      },
      {
        label: "Analytics",
        collapsed: true,
        items: [
          "guides/analytics/aggregate-and-summarize",
          "guides/analytics/collect-metrics",
        ],
      },
      {
        label: "Edge Storage",
        collapsed: true,
        items: [
          "guides/edge-storage/import-into-a-node",
          "guides/edge-storage/export-from-a-node",
          "guides/edge-storage/show-available-schemas",
          "guides/edge-storage/transform-data-at-rest",
        ],
      },
    ],
    "layers",
  ),
  section(
    "Build",
    [
      {
        label: "Packages",
        collapsed: true,
        items: [
          "guides/packages/install-a-package",
          "guides/packages/create-a-package",
          "guides/packages/test-packages",
          "guides/packages/add-operators",
          "guides/packages/add-pipelines",
          "guides/packages/add-contexts",
          "guides/packages/configure-inputs",
          "guides/packages/maintain-a-changelog",
          "guides/packages/publish-a-package",
        ],
      },
      {
        label: "Testing",
        collapsed: true,
        items: [
          "guides/testing/write-tests",
          "guides/testing/create-fixtures",
          "guides/testing/add-custom-runners",
        ],
      },
    ],
    "package",
  ),
  section(
    "Contribute",
    [
      {
        label: "Contribution",
        collapsed: true,
        items: [
          "guides/contribution/code-of-conduct",
          "guides/contribution/workflow",
          "guides/contribution/documentation",
          "guides/contribution/security",
        ],
      },
      {
        label: "Development",
        collapsed: true,
        items: [
          "guides/development/build-from-source",
          "guides/development/write-a-node-plugin",
        ],
      },
    ],
    "heart",
  ),
];

export const tutorials = [
  section(
    "Fundamentals",
    [
      "tutorials/learn-idiomatic-tql",
      "tutorials/write-a-package",
      "tutorials/map-data-to-ocsf",
    ],
    "code",
  ),
  section("Analytics", ["tutorials/plot-data-with-charts"], "chart-bar"),
];

export const explanations = [
  section(
    "Architecture",
    [
      "explanations/deployment",
      "explanations/pipeline",
      "explanations/node",
      "explanations/platform",
      "explanations/language",
    ],
    "layers",
  ),
  section(
    "Concepts",
    [
      "explanations/configuration",
      "explanations/secrets",
      "explanations/enrichment",
      "explanations/packages",
    ],
    "puzzle-piece",
  ),
  section(
    "Help",
    ["explanations/glossary", "explanations/faqs"],
    "circle-help",
  ),
];

export const reference = [
  section(
    "Language (TQL)",
    [
      "reference/types",
      "reference/expressions",
      "reference/statements",
      "reference/programs",
      { label: "Operators", link: "reference/operators" },
      { label: "Functions", link: "reference/functions" },
    ],
    "code",
  ),
  section(
    "Components",
    [
      {
        label: "Node",
        collapsed: true,
        items: ["reference/node/configuration", nodeAPISidebarGroup],
      },
      {
        label: "Platform",
        collapsed: true,
        items: [
          "reference/platform/configuration",
          "reference/platform/command-line-interface",
          platformAPISidebarGroup,
        ],
      },
    ],
    "cube",
  ),
  section(
    "Tools",
    [
      {
        label: "Test Framework",
        link: "reference/test-framework",
      },
      {
        label: "Ship Framework",
        link: "reference/ship-framework",
      },
      {
        label: "MCP Server",
        link: "reference/mcp-server",
      },
      {
        label: "Claude Marketplace",
        link: "reference/claude-plugins",
      },
    ],
    "wrench",
  ),
  // OCSF sidebar is conditionally included when generated
  ...(ocsfSidebar ? [section("Standards", [ocsfSidebar], "shield")] : []),
  section(
    "Workflows",
    [
      "reference/workflows/create-parser-package",
      "reference/workflows/create-ocsf-mapping",
    ],
    "list-checks",
  ),
];

export const integrations = [
  section(
    "Cloud Providers",
    [
      {
        label: "Amazon",
        collapsed: true,
        items: [
          "integrations/amazon",
          "integrations/amazon/msk",
          "integrations/amazon/s3",
          "integrations/amazon/security-lake",
          "integrations/amazon/sqs",
        ],
      },
      {
        label: "Google",
        collapsed: true,
        items: [
          "integrations/google/cloud-logging",
          "integrations/google/cloud-storage",
          "integrations/google/cloud-pubsub",
          "integrations/google/secops",
        ],
      },
      {
        label: "Microsoft",
        collapsed: true,
        items: [
          "integrations/microsoft/azure-blob-storage",
          "integrations/microsoft/azure-event-hubs",
          "integrations/microsoft/azure-sentinel-log-analytics",
          "integrations/microsoft/defender",
          "integrations/microsoft/windows-event-logs",
        ],
      },
    ],
    "cube",
  ),
  section(
    "Messaging",
    [
      "integrations/amqp",
      "integrations/fluent-bit",
      "integrations/kafka",
      "integrations/zeromq",
    ],
    "plug",
  ),
  section(
    "Protocols",
    [
      "integrations/email",
      "integrations/file",
      "integrations/ftp",
      "integrations/http",
      "integrations/nic",
      "integrations/syslog",
      "integrations/tcp",
      "integrations/udp",
    ],
    "layers",
  ),
  section(
    "Data Tools",
    [
      "integrations/clickhouse",
      "integrations/elasticsearch",
      "integrations/graylog",
      "integrations/opensearch",
      "integrations/snowflake",
      "integrations/splunk",
    ],
    "chart-bar",
  ),
  section(
    "Security Tools",
    [
      "integrations/sentinelone-data-lake",
      "integrations/suricata",
      "integrations/velociraptor",
      "integrations/zeek",
      "integrations/zscaler",
    ],
    "shield",
  ),
];
