// Generated by changelog.py

export const changelog_node = [
  'changelog/node/next',
  'changelog/node/v5-0-0',
];

export const changelog_platform = [
  'changelog/platform/next',
  'changelog/platform/v5-0-0',
];
