// This file is auto-generated by scripts/sync-changelog.mjs
// Do not edit manually.

// Individual project topics (children of Changelog)
export const changelogTopics = [
  {
    "label": "Tenzir Node",
    "id": "changelog-tenzir",
    "link": "changelog/tenzir",
    "icon": "seti:webpack",
    "items": [
      {
        "label": "Tenzir Node v5.x",
        "collapsed": false,
        "items": [
          "changelog/tenzir/unreleased",
          "changelog/tenzir/v5-22-1",
          "changelog/tenzir/v5-22-0",
          "changelog/tenzir/v5-21-2",
          "changelog/tenzir/v5-21-1",
          "changelog/tenzir/v5-21-0",
          "changelog/tenzir/v5-20-2",
          "changelog/tenzir/v5-20-1",
          "changelog/tenzir/v5-20-0",
          "changelog/tenzir/v5-19-0",
          "changelog/tenzir/v5-18-0",
          "changelog/tenzir/v5-17-0",
          "changelog/tenzir/v5-16-0",
          "changelog/tenzir/v5-15-0",
          "changelog/tenzir/v5-14-0",
          "changelog/tenzir/v5-13-2",
          "changelog/tenzir/v5-13-1",
          "changelog/tenzir/v5-13-0",
          "changelog/tenzir/v5-12-1",
          "changelog/tenzir/v5-12-0",
          "changelog/tenzir/v5-11-1",
          "changelog/tenzir/v5-11-0",
          "changelog/tenzir/v5-10-0",
          "changelog/tenzir/v5-9-0",
          "changelog/tenzir/v5-8-0",
          "changelog/tenzir/v5-7-0",
          "changelog/tenzir/v5-6-1",
          "changelog/tenzir/v5-6-0",
          "changelog/tenzir/v5-5-0",
          "changelog/tenzir/v5-4-1",
          "changelog/tenzir/v5-4-0",
          "changelog/tenzir/v5-3-4",
          "changelog/tenzir/v5-3-3",
          "changelog/tenzir/v5-3-2",
          "changelog/tenzir/v5-3-0",
          "changelog/tenzir/v5-2-0",
          "changelog/tenzir/v5-1-8",
          "changelog/tenzir/v5-1-7",
          "changelog/tenzir/v5-1-6",
          "changelog/tenzir/v5-1-5",
          "changelog/tenzir/v5-1-4",
          "changelog/tenzir/v5-1-3",
          "changelog/tenzir/v5-1-2",
          "changelog/tenzir/v5-1-1",
          "changelog/tenzir/v5-1-0",
          "changelog/tenzir/v5-0-1",
          "changelog/tenzir/v5-0-0"
        ]
      },
      {
        "label": "Tenzir Node v4.x",
        "collapsed": true,
        "items": [
          "changelog/tenzir/v4-32-1",
          "changelog/tenzir/v4-32-0",
          "changelog/tenzir/v4-31-2",
          "changelog/tenzir/v4-31-0",
          "changelog/tenzir/v4-30-3",
          "changelog/tenzir/v4-30-2",
          "changelog/tenzir/v4-30-1",
          "changelog/tenzir/v4-30-0",
          "changelog/tenzir/v4-29-2",
          "changelog/tenzir/v4-29-1",
          "changelog/tenzir/v4-29-0",
          "changelog/tenzir/v4-28-2",
          "changelog/tenzir/v4-28-0",
          "changelog/tenzir/v4-27-0",
          "changelog/tenzir/v4-26-0",
          "changelog/tenzir/v4-25-0",
          "changelog/tenzir/v4-24-1",
          "changelog/tenzir/v4-24-0",
          "changelog/tenzir/v4-23-1",
          "changelog/tenzir/v4-23-0",
          "changelog/tenzir/v4-22-2",
          "changelog/tenzir/v4-22-1",
          "changelog/tenzir/v4-22-0",
          "changelog/tenzir/v4-21-1",
          "changelog/tenzir/v4-21-0",
          "changelog/tenzir/v4-20-3",
          "changelog/tenzir/v4-20-2",
          "changelog/tenzir/v4-20-1",
          "changelog/tenzir/v4-20-0",
          "changelog/tenzir/v4-19-6",
          "changelog/tenzir/v4-19-5",
          "changelog/tenzir/v4-19-4",
          "changelog/tenzir/v4-19-3",
          "changelog/tenzir/v4-19-2",
          "changelog/tenzir/v4-19-1",
          "changelog/tenzir/v4-19-0",
          "changelog/tenzir/v4-18-5",
          "changelog/tenzir/v4-18-4",
          "changelog/tenzir/v4-18-3",
          "changelog/tenzir/v4-18-2",
          "changelog/tenzir/v4-18-1",
          "changelog/tenzir/v4-18-0",
          "changelog/tenzir/v4-17-4",
          "changelog/tenzir/v4-17-3",
          "changelog/tenzir/v4-17-2",
          "changelog/tenzir/v4-17-1",
          "changelog/tenzir/v4-17-0",
          "changelog/tenzir/v4-16-0",
          "changelog/tenzir/v4-15-2",
          "changelog/tenzir/v4-15-1",
          "changelog/tenzir/v4-15-0",
          "changelog/tenzir/v4-14-0",
          "changelog/tenzir/v4-13-1",
          "changelog/tenzir/v4-13-0",
          "changelog/tenzir/v4-12-2",
          "changelog/tenzir/v4-12-1",
          "changelog/tenzir/v4-12-0",
          "changelog/tenzir/v4-11-2",
          "changelog/tenzir/v4-11-0",
          "changelog/tenzir/v4-10-4",
          "changelog/tenzir/v4-10-3",
          "changelog/tenzir/v4-10-1",
          "changelog/tenzir/v4-10-0",
          "changelog/tenzir/v4-9-0",
          "changelog/tenzir/v4-8-2",
          "changelog/tenzir/v4-8-1",
          "changelog/tenzir/v4-8-0",
          "changelog/tenzir/v4-7-1",
          "changelog/tenzir/v4-7-0",
          "changelog/tenzir/v4-6-4",
          "changelog/tenzir/v4-6-3",
          "changelog/tenzir/v4-6-0",
          "changelog/tenzir/v4-5-0",
          "changelog/tenzir/v4-4-0",
          "changelog/tenzir/v4-3-0",
          "changelog/tenzir/v4-2-0",
          "changelog/tenzir/v4-1-0",
          "changelog/tenzir/v4-0-1",
          "changelog/tenzir/v4-0-0"
        ]
      },
      {
        "label": "Tenzir Node v3.x",
        "collapsed": true,
        "items": [
          "changelog/tenzir/v3-1-0",
          "changelog/tenzir/v3-0-4",
          "changelog/tenzir/v3-0-3",
          "changelog/tenzir/v3-0-2",
          "changelog/tenzir/v3-0-1",
          "changelog/tenzir/v3-0-0"
        ]
      },
      {
        "label": "Tenzir Node v2.x",
        "collapsed": true,
        "items": [
          "changelog/tenzir/v2-4-2",
          "changelog/tenzir/v2-4-1",
          "changelog/tenzir/v2-4-0",
          "changelog/tenzir/v2-3-1",
          "changelog/tenzir/v2-3-0",
          "changelog/tenzir/v2-2-0",
          "changelog/tenzir/v2-1-0",
          "changelog/tenzir/v2-0-0"
        ]
      },
      {
        "label": "Tenzir Node v1.x",
        "collapsed": true,
        "items": [
          "changelog/tenzir/v1-1-2",
          "changelog/tenzir/v1-1-1",
          "changelog/tenzir/v1-1-0",
          "changelog/tenzir/v1-0-0"
        ]
      }
    ],
    "color": "blue"
  },
  {
    "label": "Tenzir Platform",
    "id": "changelog-platform",
    "link": "changelog/platform",
    "icon": "seti:db",
    "items": [
      {
        "label": "Tenzir Platform v1.x",
        "collapsed": false,
        "items": [
          "changelog/platform/v1-25-1",
          "changelog/platform/v1-25-0",
          "changelog/platform/v1-24-0",
          "changelog/platform/v1-23-1",
          "changelog/platform/v1-23-0",
          "changelog/platform/v1-22-0",
          "changelog/platform/v1-21-0",
          "changelog/platform/v1-20-0",
          "changelog/platform/v1-19-1",
          "changelog/platform/v1-19-0",
          "changelog/platform/v1-18-0",
          "changelog/platform/v1-17-4",
          "changelog/platform/v1-17-3",
          "changelog/platform/v1-17-2",
          "changelog/platform/v1-17-1",
          "changelog/platform/v1-17-0",
          "changelog/platform/v1-16-1",
          "changelog/platform/v1-16-0",
          "changelog/platform/v1-15-0",
          "changelog/platform/v1-14-1",
          "changelog/platform/v1-14-0",
          "changelog/platform/v1-13-0",
          "changelog/platform/v1-12-0",
          "changelog/platform/v1-11-1",
          "changelog/platform/v1-10-4",
          "changelog/platform/v1-10-3",
          "changelog/platform/v1-10-2",
          "changelog/platform/v1-10-1",
          "changelog/platform/v1-10-0",
          "changelog/platform/v1-9-7",
          "changelog/platform/v1-9-6",
          "changelog/platform/v1-9-5",
          "changelog/platform/v1-9-4",
          "changelog/platform/v1-9-3",
          "changelog/platform/v1-9-2",
          "changelog/platform/v1-9-1",
          "changelog/platform/v1-9-0",
          "changelog/platform/v1-8-5",
          "changelog/platform/v1-8-4",
          "changelog/platform/v1-8-3",
          "changelog/platform/v1-8-2",
          "changelog/platform/v1-8-1",
          "changelog/platform/v1-8-0",
          "changelog/platform/v1-7-2",
          "changelog/platform/v1-7-1",
          "changelog/platform/v1-7-0",
          "changelog/platform/v1-6-1",
          "changelog/platform/v1-6-0",
          "changelog/platform/v1-5-0",
          "changelog/platform/v1-4-1",
          "changelog/platform/v1-4-0",
          "changelog/platform/v1-3-0",
          "changelog/platform/v1-2-1",
          "changelog/platform/v1-2-0",
          "changelog/platform/v1-1-2",
          "changelog/platform/v1-1-1",
          "changelog/platform/v1-1-0",
          "changelog/platform/v1-0-8",
          "changelog/platform/v1-0-7",
          "changelog/platform/v1-0-6",
          "changelog/platform/v1-0-5",
          "changelog/platform/v1-0-4",
          "changelog/platform/v1-0-3",
          "changelog/platform/v1-0-2",
          "changelog/platform/v1-0-1",
          "changelog/platform/v1-0-0"
        ]
      },
      {
        "label": "Tenzir Platform v0.x",
        "collapsed": true,
        "items": [
          "changelog/platform/v0-20-2",
          "changelog/platform/v0-20-1",
          "changelog/platform/v0-20-0",
          "changelog/platform/v0-19-1",
          "changelog/platform/v0-19-0",
          "changelog/platform/v0-18-2",
          "changelog/platform/v0-18-1",
          "changelog/platform/v0-18-0",
          "changelog/platform/v0-17-2",
          "changelog/platform/v0-17-1",
          "changelog/platform/v0-17-0",
          "changelog/platform/v0-16-0"
        ]
      }
    ],
    "color": "red"
  },
  {
    "label": "Tenzir MCP Server",
    "id": "changelog-mcp",
    "link": "changelog/mcp",
    "icon": "setting",
    "items": [
      {
        "label": "Tenzir MCP Server v0.x",
        "collapsed": false,
        "items": [
          "changelog/mcp/v0-4-5",
          "changelog/mcp/v0-4-4",
          "changelog/mcp/v0-4-3",
          "changelog/mcp/v0-4-2",
          "changelog/mcp/v0-4-1",
          "changelog/mcp/v0-4-0"
        ]
      }
    ],
    "color": "pink"
  },
  {
    "label": "Tenzir Test",
    "id": "changelog-tenzir-test",
    "link": "changelog/tenzir-test",
    "icon": "rocket",
    "items": [
      {
        "label": "Tenzir Test v0.x",
        "collapsed": false,
        "items": [
          "changelog/tenzir-test/v0-13-1",
          "changelog/tenzir-test/v0-13-0",
          "changelog/tenzir-test/v0-12-0",
          "changelog/tenzir-test/v0-11-0"
        ]
      }
    ],
    "color": "green"
  },
  {
    "label": "Tenzir Changelog",
    "id": "changelog-changelog",
    "link": "changelog/changelog",
    "icon": "open-book",
    "items": [
      {
        "label": "Tenzir Changelog v0.x",
        "collapsed": false,
        "items": [
          "changelog/changelog/v0-17-0",
          "changelog/changelog/v0-16-0",
          "changelog/changelog/v0-15-0",
          "changelog/changelog/v0-14-0",
          "changelog/changelog/v0-13-1",
          "changelog/changelog/v0-13-0",
          "changelog/changelog/v0-12-0",
          "changelog/changelog/v0-11-1",
          "changelog/changelog/v0-11-0",
          "changelog/changelog/v0-10-0",
          "changelog/changelog/v0-9-1",
          "changelog/changelog/v0-9-0",
          "changelog/changelog/v0-8-1",
          "changelog/changelog/v0-8-0",
          "changelog/changelog/v0-7-0",
          "changelog/changelog/v0-6-0",
          "changelog/changelog/v0-5-0",
          "changelog/changelog/v0-4-1",
          "changelog/changelog/v0-4-0",
          "changelog/changelog/v0-3-0",
          "changelog/changelog/v0-2-0",
          "changelog/changelog/v0-1-0"
        ]
      }
    ],
    "color": "purple"
  },
  {
    "label": "Claude Marketplace",
    "id": "changelog-claude-plugins",
    "link": "changelog/claude-plugins",
    "icon": "puzzle",
    "items": [
      {
        "label": "Claude Marketplace",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/v1-0-0"
        ]
      },
      {
        "label": "Brand Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/brand/v1-0-0",
          "changelog/claude-plugins/brand/v0-1-0"
        ]
      },
      {
        "label": "Changelog Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/changelog/v1-2-0",
          "changelog/claude-plugins/changelog/v1-1-0",
          "changelog/claude-plugins/changelog/v1-0-0",
          "changelog/claude-plugins/changelog/v0-1-0"
        ]
      },
      {
        "label": "C++ Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/cpp/unreleased"
        ]
      },
      {
        "label": "Docs Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/docs/v1-1-0",
          "changelog/claude-plugins/docs/v1-0-0",
          "changelog/claude-plugins/docs/v0-1-0"
        ]
      },
      {
        "label": "Formatter Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/formatter/v1-1-0",
          "changelog/claude-plugins/formatter/v1-0-0",
          "changelog/claude-plugins/formatter/v0-1-0"
        ]
      },
      {
        "label": "Git Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/git/v1-0-0",
          "changelog/claude-plugins/git/v0-1-0"
        ]
      },
      {
        "label": "Meta Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/meta/v1-1-0",
          "changelog/claude-plugins/meta/v1-0-0",
          "changelog/claude-plugins/meta/v0-1-0"
        ]
      },
      {
        "label": "Prose Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/prose/v1-0-0",
          "changelog/claude-plugins/prose/v0-1-0"
        ]
      },
      {
        "label": "Python Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/python/v1-0-0",
          "changelog/claude-plugins/python/v0-1-0"
        ]
      },
      {
        "label": "TQL Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/tql/v1-0-0",
          "changelog/claude-plugins/tql/v0-1-0"
        ]
      },
      {
        "label": "Writing Plugin",
        "collapsed": true,
        "items": [
          "changelog/claude-plugins/writing/v1-0-0",
          "changelog/claude-plugins/writing/v0-1-0"
        ]
      }
    ],
    "color": "orange"
  },
  {
    "label": "Tree-sitter TQL",
    "id": "changelog-tree-sitter-tql",
    "link": "changelog/tree-sitter-tql",
    "icon": "sun",
    "items": [
      {
        "label": "Tree-sitter TQL v1.x",
        "collapsed": false,
        "items": [
          "changelog/tree-sitter-tql/v1-0-0"
        ]
      }
    ],
    "color": "yellow"
  }
];

// Parent mappings for the dropdown
export const changelogTopicParents = {
  "Tenzir Node": "Changelog",
  "Tenzir Platform": "Changelog",
  "Tenzir MCP Server": "Changelog",
  "Tenzir Test": "Changelog",
  "Tenzir Changelog": "Changelog",
  "Claude Marketplace": "Changelog",
  "Tree-sitter TQL": "Changelog"
};

// Topic path mappings for starlight-sidebar-topics
export const changelogTopicPaths = {
  "changelog-tenzir": [
    "/changelog/tenzir",
    "/changelog/tenzir/**/*"
  ],
  "changelog-platform": [
    "/changelog/platform",
    "/changelog/platform/**/*"
  ],
  "changelog-mcp": [
    "/changelog/mcp",
    "/changelog/mcp/**/*"
  ],
  "changelog-tenzir-test": [
    "/changelog/tenzir-test",
    "/changelog/tenzir-test/**/*"
  ],
  "changelog-changelog": [
    "/changelog/changelog",
    "/changelog/changelog/**/*"
  ],
  "changelog-claude-plugins": [
    "/changelog/claude-plugins",
    "/changelog/claude-plugins/**/*"
  ],
  "changelog-tree-sitter-tql": [
    "/changelog/tree-sitter-tql",
    "/changelog/tree-sitter-tql/**/*"
  ]
};
