// Auto-generated by scripts/sync-changelog.mjs - do not edit manually.
// This stub exists so TypeScript builds succeed before sync runs.
// Run 'pnpm sync:changelog' to populate with real changelog data.
export const changelogTopics: never[] = [];
export const changelogTopicParents: Record<string, string> = {};
