name: Code Quality

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lefthook:
    name: Lefthook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Validate Lefthook config
        run: bun run lefthook:validate

      - name: Run Lefthook
        run: bun run lint
