name: Nightly Link Check

on:
  workflow_dispatch:
  schedule:
    # Run nightly at 02:00 UTC
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  linkcheck:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.TENZIR_BOT_GITHUB_TOKEN }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run link check
        env:
          RUN_LINK_CHECK: true
        run: pnpm build

      - name: Create issue if links are broken
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Broken links detected - ${new Date().toISOString().split('T')[0]}`;
            const body = `Automated link checking has detected broken links in the documentation.

            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please review and fix the broken links found during the build process.

            This issue was automatically created by the link checking workflow.`;

            // Check if there's already an open issue for broken links
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: 'issues',
              state: 'open',
              labels: 'broken-links',
            });

            if (issues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: 'issues',
                title: title,
                body: body,
                labels: [],
              });
            } else {
              // Update existing issue with new run information
              const existingIssue = issues[0];
              const updatedBody = `${existingIssue.body}

            ---

            **New broken links detected:** ${new Date().toISOString().split('T')[0]}
            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: 'issues',
                issue_number: existingIssue.number,
                body: updatedBody,
              });
            }
